#!/usr/bin/env bash
# this script is an infinite loop which print To infinity and beyond and it can't be stopped with ctr c untill you kill the process
trap '' INT
while true; do
	echo "To infinity and beyond"
done
