#!/usr/bin/env bash
# displaying Best School 10 times while 9nt display it then hi
counter=1
while [ "$counter" -le 10 ]
do
	if [ "$counter" -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	counter=$(("$counter" + 1))
done
	
