#!/usr/bin/env bash
# displaying numbers from 1 20 but when 4, 9, and 17 add bad luck from china, japan, and italy respectively
counter=1
while [ "$counter" -le 20 ]
do
	case $counter in
	4)
		echo "$counter"
		echo "bad luck from China"
			;;
	9)
		echo "$counter"
		echo "bad luck from Japan"
		;;
	17)
		echo "$counter"
		echo "bad luck from Italy"
		;;
	*)
		echo "$counter"
		;;
	esac
	counter=$(("$counter" + 1))
done
